services:
  app:
    build: .
    ports:
      - 8888:8888
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=222
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
  redis:
    image: redis
