services:
  app:
    build: .
    ports:
      - 8888:8888
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=222
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - netapp
  redis:
    image: redis
    volumes:
      - data_redis:/data

    networks:
      - netapp
volumes:
  data_postgres: {}
  data_redis: {}
networks:
  netapp: {}
