services:
  app:
    image: ghcr.io/yusufbahtiarr/fgo24-be-crud:latest
    ports:
      - "9703:8888"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - netapp

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - netapp

  redis:
    image: redis:latest
    volumes:
      - data_redis:/data
    networks:
      - netapp

volumes:
  data_postgres: {}
  data_redis: {}

networks:
  netapp: {}
