name: Push Backend Image to GHCR & Deploy
run-name: Release and Deploy to Server
on: [push]
jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-server:
    needs: push-image-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 9701 yusuf@146.190.102.54 << 'EOF'
            cd /home/yusuf/fgo24-be-crud
            docker-compose pull
            docker-compose down
            docker-compose up -d
          EOF
